In [2]:
import numpy as np
nutrient_needs=np.array([
    [120,60,80],
    [150,75,160],
    [100,50,70]
])
fertilizer_composition=np.array([
    [0.20,0.19,0.15],
    [0.15,0.20,0.10],
    [0.10,0.15,0.25]
])
print('nutrient requirements(kg/ha):')
print(nutrient_needs)
print('\fertilizer composition(%):')
print(fertilizer_composition)
print('\ntransposed nutrient needs(nutrients*crops):')
print(nutrient_needs.T)
total_nutrients_per_crop=np.sum(nutrient_needs,axis=1)
print(f'\ntotal nutrients needed per crop:{total_nutrients_per_crop} kg\ha')
fertilizer_application=np.array([100,100,100])
nutrients_delivered=np.dot(fertilizer_application,fertilizer_composition)
print(f'\nutrients from 100kg each fertilizer:{nutrients_delivered}')
det=np.linalg.det(fertilizer_composition)
print(f'\ndeterminant of fertilizer matrix:{det:.6f}')
scaling=np.eye(3)*1.1
enhanced_needs=np.dot(nutrient_needs,scaling)
print('\nenhanced nutrient needs(10% increase):')
print(enhanced_needs)

nutrient requirements(kg/ha):
[[120  60  80]
 [150  75 160]
 [100  50  70]]
ertilizer composition(%):
[[0.2  0.19 0.15]
 [0.15 0.2  0.1 ]
 [0.1  0.15 0.25]]

transposed nutrient needs(nutrients*crops):
[[120 150 100]
 [ 60  75  50]
 [ 80 160  70]]

total nutrients needed per crop:[260 385 220] kg\ha

utrients from 100kg each fertilizer:[45. 54. 50.]

determinant of fertilizer matrix:0.002150

enhanced nutrient needs(10% increase):
[[132.   66.   88. ]
 [165.   82.5 176. ]
 [110.   55.   77. ]]


<>:19: SyntaxWarning: invalid escape sequence '\h'
<>:19: SyntaxWarning: invalid escape sequence '\h'
/tmp/ipython-input-240215490.py:19: SyntaxWarning: invalid escape sequence '\h'
  print(f'\ntotal nutrients needed per crop:{total_nutrients_per_crop} kg\ha')
