In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [6]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
a=np.array(42)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print('number of dimensions:',arr.ndim)

[1 2 3 4]
number of dimensions: 1


In [18]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [21]:

import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [26]:
arr=np.array([1,2,3,4,5])
arr_2d=np.array([[1,2,3],[4,5,6]])
zeros=np.zeros((3,4))
ones=np.ones((2,3))
range_arr=np.arange(0,10,2)
linespace=np.linspace(0,1,5)
identity=np.eye(3)
random_arr=np.random.rand(3,4)
print(zeros)
print("---------------------")
print(ones)
print("---------------------")
print(range_arr)
print("---------------------")
print(linespace)
print("---------------------")
print(identity)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
---------------------
[[1. 1. 1.]
 [1. 1. 1.]]
---------------------
[0 2 4 6 8]
---------------------
[0.   0.25 0.5  0.75 1.  ]
---------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [28]:
print(a.dtype)

int64


In [29]:
print(a.size)

6


In [30]:
print(a.ndim)

2


In [31]:
np.sum(a)

np.int64(21)

In [32]:
np.mean(a,axis=0)
np.mean(a,axis=1)

array([2., 5.])

In [35]:
np.max(a)
np.min(a)

np.int64(1)

In [36]:
b=np.array([10,40,30])
np.argmax(b)

np.int64(1)

In [37]:
crop_yields=np.array([
    [12.2,13.2,14.1,13.8,15.2],
    [10.3,11.5,10.8,12.1,11.9],
    [15.1,14.8,16.2,15.5,16.8],
    [11.2,10.9,12.3,11.7,12.8]
])
print('crop yields array(tons):')
print(crop_yields)
print(f'\nShape:{crop_yields.shape}')
print(f'Data type:{crop_yields.dtype}')
print(f'Total elements:{crop_yields.size}')
print(f'Number of dimensions:{crop_yields.ndim}')


crop yields array(tons):
[[12.2 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

Shape:(4, 5)
Data type:float64
Total elements:20
Number of dimensions:2


In [ ]:
total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)
print(f'\nTotal production:{total_yield}tons')
print(f'Average per farm:{avg_yield_per_farm}tons')
print(f'Average per season:{avg_yield_per_season}tons')
print(f'maximum yield:{max_yield}tons')
print(f'minimum yield:{min_yield}tons')

